name: Deploy React para GitHub Pages

on:
  push:
    branches:
      - main  # rodar deploy sempre que fizer push na main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages    # branch que vai receber o build
          publish_dir: ./build        # pasta do build
          force_orphan: true          # cria branch do zero, evitando conflitos antigos